version: "3.9"

services:
  api:
    build: .
    container_name: book_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  scheduler:
    build: .
    container_name: book_scheduler
    env_file:
      - .env
    depends_on:
      - api
      - mongo
      - redis
    command: python -m scheduler.scheduler
    restart: always

  mongo:
    image: mongo:7
    container_name: book_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: book_redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
